version: '3.8'

services:
  client:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
    depends_on:
      - server

  server:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
